version: '3'
services:
  redis:
    image: redis:3.2.11
  db:
    image: postgres:alpine
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails_project
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  jobs:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec sidekiq"
    volumes:
      - .:/rails_project
    depends_on:
      - db
      - redis